app/accounts/urls.py
from __future__ import absolute_import, division, unicode_literals
from future.builtins import (  # noqa
    ascii, bytes, chr, dict, filter, hex, input, int, list, map, next, object,
    oct, open, pow, range, round, str, super, zip
)

from django.conf.urls import patterns, url
from django.utils.translation import ugettext_lazy as _

from .views import ChangePasswordView, SignInView, SignOutView

urlpatterns = patterns(
    '',
    url(
        _(r'^sign_in/$'),
        SignInView.as_view(),
        name='sign_in'
    ),
    url(
        _(r'^sign_out/$'),
        SignOutView.as_view(),
        name='sign_out'
    ),
    url(
        _(r'^change_password/$'),
        ChangePasswordView.as_view(),
        name='change_password'
    )
)

app/app/urls.py
from __future__ import absolute_import, division, unicode_literals
from future.builtins import (  # noqa
    ascii, bytes, chr, dict, filter, hex, input, int, list, map, next, object,
    oct, open, pow, range, round, str, super, zip
)

from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.admin.sites import AlreadyRegistered
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.contrib.sitemaps.views import sitemap
from django.db.models import get_models
from django.shortcuts import get_object_or_404
from django.views.i18n import javascript_catalog
from hijack import views as hijack_views
from hijack.helpers import login_user as hijack_login_user
from hijack.urls import urlpatterns as hijack_urlpatterns

from content.sitemaps import IndexSitemap
from content.views import (
    FaviconRedirectView, IndexTemplateView, RobotsTemplateView, WatchVideoView
)

from .conf import settings
from .utils import cache_view

admin.autodiscover()


@staff_member_required
def login_with_id(request, user_id):
    user = get_object_or_404(
        get_user_model(),
        pk=user_id
    )
    return hijack_login_user(request, user)


hijack_views.login_with_id = login_with_id


hijack_login_with_id_urlpattern = url(
    r'^(?P<user_id>[\-a-z0-9]{32,36})/$',
    'hijack.views.login_with_id',
    name='login_with_id'
)

for urlpattern in hijack_urlpatterns:
    if 'user_id' in urlpattern._regex:
        login_with_id_pattern = urlpattern
        break

hijack_urlpatterns.remove(login_with_id_pattern)

hijack_urlpatterns.append(
    hijack_login_with_id_urlpattern
)


if settings.DISABLE_DELETE_SELECTED:
    try:
        admin.site.disable_action('delete_selected')
    except KeyError:
        pass


if settings.MODELS_AUTO_REGISTRATION:
    for model in get_models():
        try:
            admin.site.register(model)
        except AlreadyRegistered:
            pass


handler400 = 'app.views.handler400'
handler403 = 'app.views.handler403'
handler404 = 'app.views.handler404'
handler500 = 'app.views.handler500'


urlpatterns = patterns('')


urlpatterns += patterns(
    '',
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts')
    )
)


if settings.DEBUG:
    # static
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    # media
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


if settings.USE_DOCS:
    urlpatterns += patterns(
        '',
        url(
            r'^admin/doc/api/',
            include('rest_framework_swagger.urls')
        ),
        url(
            r'^admin/doc/',
            include('django.contrib.admindocs.urls')
        ),
    )


sitemaps = {
    'index': IndexSitemap,
}


js_info_dict = {
    'domain': 'djangojs',
    'packages': [
        'yaga'
    ]
}


urlpatterns += patterns(
    '',
    # sitemap
    url(
        r'^sitemap\.xml$',
        cache_view(sitemap),
        {
            'sitemaps': sitemaps
        },
        name='sitemap'
    ),
    # favicon
    url(
        r'^favicon\.ico$',
        FaviconRedirectView.as_view()
    ),
    # robots
    url(
        r'^robots\.txt$',
        RobotsTemplateView.as_view()
    ),
    # django i18 js
    url(
        r'^jsi18n/$',
        cache_view(javascript_catalog),
        js_info_dict,
        name='djangojs'
    ),
    # admin
    url(
        r'^admin/',
        include(admin.site.urls)
        # include(site.urls)
    ),
    # hijack
    url(
        r'^hijack/',
        include(hijack_urlpatterns)
    ),
    # index
    url(
        r'^$',
        IndexTemplateView.as_view(),
        name='index'
    ),
    # yaga
    url(
        r'^yaga/',
        include('yaga.urls', namespace='yaga')
    ),
    url(
        r'^v/(?P<post_short_id>[A-Za-z0-9]{8})$',
        WatchVideoView.as_view()
    ),
)

app/templates/base.html
{% load static %}
{% load i18n %}

{% load compress %}
{% load activeurl %}

{% load snless %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" class="no-js">
    <head>
        {% block head %}
            {% block meta %}
                <meta charset="utf-8">
                <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
            {% endblock %}
            {% snless %}
                <title>
                    {% block title %}
                        {% trans 'Project' %}
                    {% endblock %}
                </title>
            {% endsnless %}
            {% block seo %}
                {% snless %}
                    <meta name="description" content="
                        {% block description %}
                            {% trans 'Description' %}
                        {% endblock %}
                    ">
                {% endsnless %}
            {% endblock %}
            {% block css %}
                {% compress css %}
                    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}" type="text/css">
                    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}" type="text/css">
                    <link rel="stylesheet" href="{% static 'bootstrap-select/dist/css/bootstrap-select.css' %}" type="text/css">
                    <link rel="stylesheet" href="{% static 'bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.css' %}" type="text/css">
                    <link rel="stylesheet" href="{% static 'video.js/dist/video-js.css' %}" type="text/css">
                {% endcompress %}
            {% endblock %}
            {% block extra_css %}
                {% compress css %}
                    <link rel="stylesheet" type="text/stylus" href="{% static 'frontend/stylus/main.styl' %}">
                {% endcompress %}
            {% endblock %}
            {% block extra_css_plain %}
            {% endblock %}
            {% block djnagojs %}
                <script type="text/javascript" src="{% url 'djangojs' %}"></script>
            {% endblock %}
            {% block js %}
                {% compress js %}
                    <script type="text/javascript" src="{% static 'modernizr/modernizr.js' %}"></script>
                    <script type="text/javascript" src="{% static 'respond/dest/respond.src.js' %}"></script>
                    <script type="text/javascript" src="{% static 'json3/lib/json3.js' %}"></script>
                    <script type="text/javascript" src="{% static 'jquery/dist/jquery.js' %}"></script>
                    <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
                    <script type="text/javascript" src="{% static 'bootstrap-select/dist/js/bootstrap-select.js' %}"></script>
                    <script type="text/javascript" src="{% static 'bootstrap-switch/dist/js/bootstrap-switch.js' %}"></script>
                    <script type="text/javascript" src="{% static 'underscore/underscore.js' %}"></script>
                    <script type="text/javascript" src="{% static 'video.js/dist/video.js' %}"></script>
                {% endcompress %}
            {% endblock %}
            {% block extra_js_plain %}
                <script type="text/javascript">
                    'use strict';

                    var LANGUAGE_CODE = '{{ LANGUAGE_CODE }}';
                </script>
            {% endblock %}
            {% block extra_js %}
                {% compress js %}
                    <script type="text/coffeescript" src="{% static 'frontend/coffee/main.coffee' %}"></script>
                {% endcompress %}
            {% endblock %}
            {% block apple %}
                <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'frontend/img/apple-touch-icon-144x144-precomposed.png' %}">
                <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'frontend/img/apple-touch-icon-114x114-precomposed.png' %}">
                <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'frontend/img/apple-touch-icon-72x72-precomposed.png' %}">
                <link rel="apple-touch-icon-precomposed" href="{% static 'frontend/img/apple-touch-icon-57x57-precomposed.png' %}">
            {% endblock %}
            {% block favicon %}
                <link rel="shortcut icon" href="{% static favicon %}">
            {% endblock %}
            {% block extra_head %}
            {% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
            {% block nav %}
                <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-class">
                                <span class="sr-only">{% trans 'Toggle navigation' %}</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand brand" href="{% url 'index' %}">
                                {% trans 'Project' %}
                            </a>
                        </div>
                        <div class="collapse navbar-collapse navbar-class">
                            {% block nav_user %}
                                {% if request.user.is_authenticated %}
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <i class="fa fa-user"></i>
                                                {{ request.user.get_username }}
                                                <b class="caret"></b>
                                            </a>
                                            {% activeurl %}
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <a href="{% url 'accounts:change_password' %}">
                                                            <i class="fa fa-pencil-square-o"></i>
                                                            {% trans 'Change password' %}
                                                        </a>
                                                    </li>
                                                    <li class="divider"></li>
                                                    <li>
                                                        <a href="{% url 'accounts:sign_out' %}">
                                                            <i class="fa fa-sign-out"></i>
                                                            {% trans 'Sign out' %}
                                                        </a>
                                                    </li>
                                                </ul>
                                            {% endactiveurl %}
                                        </li>
                                    </ul>
                                {% else %}
                                    {% activeurl %}
                                        <ul class="nav navbar-nav navbar-right">
                                            <li>
                                                <a href="{% url 'accounts:sign_in' %}">
                                                    <i class="fa fa-sign-in"></i>
                                                    {% trans 'Sign in' %}
                                                </a>
                                            </li>
                                        </ul>
                                    {% endactiveurl %}
                                {% endif %}
                            {% endblock %}
                            {% block nav_content %}
                                {% activeurl %}
                                    <ul class="nav navbar-nav">
                                        <li>
                                            <a href="{% url 'index' %}">
                                                <i class="fa fa-slideshare"></i>
                                                {% trans 'Index' %}
                                            </a>
                                        </li>
                                        {% include 'yaga/nav.html' %}
                                    </ul>
                                {% endactiveurl %}
                            {% endblock %}
                        </div>
                    </div>
                </nav>
            {% endblock %}

            <div class="section">
                <div class="container">
                    {% block messages %}
                        {% if messages %}
                            <div id="messages">
                                {% for message in messages %}
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                                    &times;
                                                </button>
                                                {{ message }}
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endblock %}

                    {% block container %}
                    {% endblock %}
                </div>
            </div>

            {% block footer %}
                <div class="container">
                    <hr>
                    <footer>
                        <div class="row">
                            <div class="col-md-12">
                                {% block copyright %}
                                    <p class="float-right">
                                        {% trans 'copyright' %} {{ now.year }}
                                    </p>
                                {% endblock %}
                            </div>
                        </div>
                    </footer>
                </div>
            {% endblock %}

            {% block analytics %}
                <script type="text/javascript">
                    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                    ga('create', '{{ settings.CONTENT_GA_ID }}', 'auto');
                    ga('send', 'pageview');
                </script>
            {% endblock %}
        {% endblock %}
    </body>
</html>